const inventoryItems = [
  // Fruits
  { name: "apple", type: "Fruits" },
  { name: "banana", type: "Fruits" },
  { name: "orange", type: "Fruits" },
  { name: "strawberry", type: "Fruits" },
  { name: "grape", type: "Fruits" },
  { name: "pineapple", type: "Fruits" },
  { name: "blueberry", type: "Fruits" },
  { name: "watermelon", type: "Fruits" },
  { name: "kiwi", type: "Fruits" },
  { name: "mango", type: "Fruits" },
  { name: "lemon", type: "Fruits" },
  { name: "avocado", type: "Fruits" },
  { name: "tomato", type: "Fruits" },

  // Vegetables
  { name: "carrot", type: "Vegetables" },
  { name: "broccoli", type: "Vegetables" },
  { name: "spinach", type: "Vegetables" },
  { name: "cucumber", type: "Vegetables" },
  { name: "potato", type: "Vegetables" },
  { name: "sweet potato", type: "Vegetables" },
  { name: "onion", type: "Vegetables" },
  { name: "bell pepper", type: "Vegetables" },
  { name: "zucchini", type: "Vegetables" },
  { name: "cauliflower", type: "Vegetables" },
  { name: "garlic", type: "Vegetables" },
  { name: "lettuce", type: "Vegetables" },
  { name: "cabbage", type: "Vegetables" },
  { name: "green beans", type: "Vegetables" },
  { name: "celery", type: "Vegetables" },
  { name: "asparagus", type: "Vegetables" },
  { name: "mushrooms", type: "Vegetables" },
  { name: "eggplant", type: "Vegetables" },
  { name: "red onion", type: "Vegetables" },
  { name: "green onion", type: "Vegetables" },
  { name: "bean sprouts", type: "Vegetables" },
  { name: "butternut squash", type: "Vegetables" },

  // Grains
  { name: "bread", type: "Grains" },
  { name: "rice", type: "Grains" },
  { name: "pasta", type: "Grains" },
  { name: "quinoa", type: "Grains" },
  { name: "oats", type: "Grains" },
  { name: "tortilla", type: "Grains" },
  { name: "cornmeal", type: "Grains" },
  { name: "spaghetti", type: "Grains" },
  { name: "noodles", type: "Grains" },
  { name: "taco shells", type: "Grains" },
  { name: "gluten-free flour", type: "Grains" },
  { name: "egg noodles", type: "Grains" },

  // Protein
  { name: "chicken", type: "Protein" },
  { name: "tofu", type: "Protein" },
  { name: "eggs", type: "Protein" },
  { name: "beef", type: "Protein" },
  { name: "lentils", type: "Protein" },
  { name: "bacon", type: "Protein" },
  { name: "turkey", type: "Protein" },
  { name: "pork", type: "Protein" },
  { name: "shrimp", type: "Protein" },
  { name: "fish", type: "Protein" },
  { name: "salmon", type: "Protein" },
  { name: "ground beef", type: "Protein" },
  { name: "chickpeas", type: "Protein" },
  { name: "lamb", type: "Protein" },
  { name: "chicken wings", type: "Protein" },
  { name: "clams", type: "Protein" },
  { name: "falafel", type: "Protein" },
  { name: "peanut", type: "Protein" },

  // Dairy
  { name: "milk", type: "Dairy" },
  { name: "cheese", type: "Dairy" },
  { name: "butter", type: "Dairy" },
  { name: "cream", type: "Dairy" },
  { name: "sour cream", type: "Dairy" },
  { name: "whipped cream", type: "Dairy" },
  { name: "mozzarella", type: "Dairy" },
  { name: "almond milk", type: "Dairy" },
  { name: "soy milk", type: "Dairy" },
  { name: "coconut milk", type: "Dairy" },
  { name: "feta cheese", type: "Dairy" },
  { name: "parmesan", type: "Dairy" },
  { name: "cheddar cheese", type: "Dairy" },

  // Other
  { name: "flour", type: "Other" },
  { name: "salt", type: "Other" },
  { name: "pepper", type: "Other" },
  { name: "olive oil", type: "Other" },
  { name: "vinegar", type: "Other" },
  { name: "sugar", type: "Other" },
  { name: "honey", type: "Other" },
  { name: "ketchup", type: "Other" },
  { name: "mustard", type: "Other" },
  { name: "mayonnaise", type: "Other" },
  { name: "bbq sauce", type: "Other" },
  { name: "soy sauce", type: "Other" },
  { name: "salsa", type: "Other" },
  { name: "chips", type: "Other" },
  { name: "pretzels", type: "Other" },
  { name: "popcorn", type: "Other" },
  { name: "cookies", type: "Other" },
  { name: "crackers", type: "Other" },
  { name: "candy", type: "Other" },
  { name: "jam", type: "Other" },
  { name: "jelly", type: "Other" },
  { name: "maple syrup", type: "Other" },
  { name: "pasta sauce", type: "Other" },
  { name: "chocolate", type: "Other" },
  { name: "oreo", type: "Other" },
  { name: "granola bar", type: "Other" },
  { name: "beef jerky", type: "Other" },
  { name: "nutella", type: "Other" },
  { name: "hot sauce", type: "Other" },
  { name: "biscuits", type: "Other" },
  { name: "croutons", type: "Other" },
  { name: "coconut oil", type: "Other" },
  { name: "raisins", type: "Other" },
  { name: "pickles", type: "Other" },
  { name: "tea", type: "Other" },
  { name: "coffee", type: "Other" },
  { name: "instant noodles", type: "Other" },
  { name: "bread crumbs", type: "Other" },
  { name: "tomato paste", type: "Other" },
  { name: "cornstarch", type: "Other" },
  { name: "pancake mix", type: "Other" },
  { name: "protein powder", type: "Other" },
  { name: "baking powder", type: "Other" },
  { name: "chia seeds", type: "Other" },
  { name: "oregano", type: "Other" },
  { name: "cinnamon", type: "Other" },
  { name: "syrup", type: "Other" },
  { name: "black pepper", type: "Other" },
  { name: "cumin", type: "Other" },
  { name: "caesar dressing", type: "Other" },
  { name: "basil", type: "Other" },
  { name: "balsamic vinegar", type: "Other" },
  { name: "pumpkin", type: "Other" },
  { name: "ginger", type: "Other" },
  { name: "parsley", type: "Other" },
  { name: "lime", type: "Other" },
  { name: "rosemary", type: "Other" },
  { name: "cilantro", type: "Other" },
  { name: "tomato sauce", type: "Other" },
  { name: "vegetable broth", type: "Other" },
  { name: "curry powder", type: "Other" },
  { name: "cocoa powder", type: "Other" },
  { name: "sesame oil", type: "Other" },
  { name: "nori", type: "Other" },
  { name: "pine nuts", type: "Other" },
  { name: "green peas", type: "Other" },
  { name: "garlic powder", type: "Other" }
];