const recipes = [
    { name: "Vegan Pancakes", ingredients: ["flour", "almond milk", "banana", "baking powder"], dietary: ["vegan", "dairy-free", "egg-free"] },
    { name: "Gluten-Free Brownies", ingredients: ["gluten-free flour", "cocoa powder", "sugar", "egg"], dietary: ["gluten-free"] },
    { name: "Vegetarian Pizza", ingredients: ["flour", "tomato sauce", "cheese", "bell pepper", "olive oil"], dietary: ["vegetarian"] },
    { name: "Dairy-Free Smoothie", ingredients: ["banana", "spinach", "almond milk", "chia seeds"], dietary: ["dairy-free", "vegan"] },
    { name: "Chicken Salad", ingredients: ["chicken", "lettuce", "tomato", "olive oil", "lemon"], dietary: ["gluten-free", "dairy-free"] },
    { name: "Keto Avocado Salad", ingredients: ["avocado", "lettuce", "bacon", "egg", "olive oil"], dietary: ["keto", "gluten-free", "dairy-free"] },
    { name: "Spaghetti Carbonara", ingredients: ["spaghetti", "egg", "bacon", "parmesan", "black pepper"], dietary: [] },
    { name: "Greek Salad", ingredients: ["cucumber", "tomato", "feta cheese", "olive oil", "oregano"], dietary: ["vegetarian", "gluten-free"] },
    { name: "Stuffed Bell Peppers", ingredients: ["bell pepper", "ground beef", "rice", "tomato sauce", "cheese"], dietary: ["gluten-free"] },
    { name: "Quinoa Salad", ingredients: ["quinoa", "cucumber", "tomato", "olive oil", "feta cheese"], dietary: ["vegetarian", "gluten-free"] },
    { name: "Beef Tacos", ingredients: ["taco shells", "ground beef", "lettuce", "cheese", "sour cream"], dietary: [] },
    { name: "Chickpea Stew", ingredients: ["chickpeas", "tomato", "spinach", "cumin", "onion"], dietary: ["vegan", "gluten-free", "dairy-free"] },
    { name: "Egg Fried Rice", ingredients: ["rice", "egg", "soy sauce", "green peas", "carrot"], dietary: ["vegetarian"] },
    { name: "Lentil Soup", ingredients: ["lentils", "carrot", "onion", "celery", "garlic"], dietary: ["vegan", "gluten-free", "dairy-free"] },
    { name: "Caesar Salad", ingredients: ["lettuce", "croutons", "parmesan", "caesar dressing", "chicken"], dietary: [] },
    { name: "Apple Pie", ingredients: ["apples", "flour", "butter", "sugar", "cinnamon"], dietary: ["vegetarian"] },
    { name: "Vegetable Stir Fry", ingredients: ["broccoli", "carrot", "bell pepper", "soy sauce", "sesame oil"], dietary: ["vegan", "gluten-free", "dairy-free"] },
    { name: "Falafel Wrap", ingredients: ["falafel", "tortilla", "lettuce", "tomato", "hummus"], dietary: ["vegan", "dairy-free"] },
    { name: "French Toast", ingredients: ["bread", "egg", "milk", "cinnamon", "syrup"], dietary: ["vegetarian"] },
    { name: "Clam Chowder", ingredients: ["clams", "potato", "onion", "cream", "bacon"], dietary: ["gluten-free"] },
    { name: "Beef Stroganoff", ingredients: ["beef", "mushrooms", "onion", "sour cream", "egg noodles"], dietary: [] },
    { name: "Shrimp Scampi", ingredients: ["shrimp", "garlic", "butter", "lemon", "pasta"], dietary: [] },
    { name: "Grilled Cheese Sandwich", ingredients: ["bread", "cheese", "butter"], dietary: ["vegetarian"] },
    { name: "Turkey Sandwich", ingredients: ["turkey", "bread", "lettuce", "tomato", "mayonnaise"], dietary: [] },
    { name: "Pasta Primavera", ingredients: ["pasta", "zucchini", "carrot", "bell pepper", "parmesan"], dietary: ["vegetarian"] },
    { name: "BBQ Chicken Wings", ingredients: ["chicken wings", "bbq sauce", "garlic powder", "pepper"], dietary: ["gluten-free"] },
    { name: "Eggplant Parmesan", ingredients: ["eggplant", "flour", "cheese", "tomato sauce"], dietary: ["vegetarian"] },
    { name: "Minestrone Soup", ingredients: ["beans", "tomato", "zucchini", "pasta", "carrot"], dietary: ["vegetarian", "dairy-free"] },
    { name: "Caprese Salad", ingredients: ["tomato", "mozzarella", "basil", "olive oil", "balsamic vinegar"], dietary: ["vegetarian", "gluten-free"] },
    { name: "Salmon with Asparagus", ingredients: ["salmon", "asparagus", "lemon", "olive oil"], dietary: ["gluten-free", "dairy-free"] },
    { name: "Broccoli Cheddar Soup", ingredients: ["broccoli", "cheddar cheese", "milk", "onion"], dietary: ["vegetarian"] },
    { name: "Pumpkin Pie", ingredients: ["pumpkin", "flour", "sugar", "egg", "cinnamon"], dietary: ["vegetarian"] },
    { name: "Fish Tacos", ingredients: ["fish", "taco shells", "lettuce", "sour cream", "salsa"], dietary: ["gluten-free"] },
    { name: "Oatmeal", ingredients: ["oats", "milk", "cinnamon", "sugar"], dietary: ["vegetarian"] },
    { name: "Avocado Toast", ingredients: ["bread", "avocado", "salt", "pepper"], dietary: ["vegan", "dairy-free"] },
    { name: "Chicken Alfredo", ingredients: ["chicken", "pasta", "cream", "parmesan", "garlic"], dietary: [] },
    { name: "Butternut Squash Soup", ingredients: ["butternut squash", "onion", "garlic", "vegetable broth"], dietary: ["vegan", "gluten-free", "dairy-free"] },
    { name: "Spinach and Mushroom Omelette", ingredients: ["egg", "spinach", "mushrooms", "cheese"], dietary: ["vegetarian"] },
    { name: "Garlic Bread", ingredients: ["bread", "garlic", "butter", "parsley"], dietary: ["vegetarian"] },
    { name: "Chicken Curry", ingredients: ["chicken", "coconut milk", "curry powder", "onion", "tomato"], dietary: ["dairy-free"] },
    { name: "Pad Thai", ingredients: ["rice noodles", "shrimp", "peanut", "bean sprouts", "lime"], dietary: ["gluten-free"] },
    { name: "Eggplant Stir Fry", ingredients: ["eggplant", "soy sauce", "garlic", "ginger", "green onion"], dietary: ["vegan", "dairy-free"] },
    { name: "Roast Beef", ingredients: ["beef", "potato", "carrot", "onion"], dietary: ["gluten-free", "dairy-free"] },
    { name: "Lamb Chops", ingredients: ["lamb", "rosemary", "garlic", "olive oil"], dietary: ["gluten-free"] },
    { name: "Cornbread", ingredients: ["cornmeal", "flour", "sugar", "egg", "milk"], dietary: ["vegetarian"] },
    { name: "Pesto Pasta", ingredients: ["pasta", "basil", "parmesan", "pine nuts", "olive oil"], dietary: ["vegetarian"] },
    { name: "Chicken Noodle Soup", ingredients: ["chicken", "noodles", "carrot", "celery", "onion"], dietary: [] },
    { name: "Mango Salsa", ingredients: ["mango", "red onion", "cilantro", "lime"], dietary: ["vegan", "gluten-free", "dairy-free"] },
    { name: "Sushi Rolls", ingredients: ["rice", "nori", "salmon", "cucumber", "avocado"], dietary: ["gluten-free"] },
    { name: "Tomato Basil Soup", ingredients: ["tomato", "basil", "cream", "onion"], dietary: ["vegetarian"] },
    { name: "Mashed Potatoes", ingredients: ["potatoes", "butter", "milk"], dietary: ["vegetarian", "gluten-free"] },
    { name: "Ratatouille", ingredients: ["zucchini", "eggplant", "bell pepper", "tomato", "olive oil"], dietary: ["vegan", "gluten-free", "dairy-free"] },
    { name: "Pasta Bolognese", ingredients: ["pasta", "ground beef", "tomato", "onion", "garlic"], dietary: [] },
    { name: "Tofu Stir Fry", ingredients: ["tofu", "broccoli", "soy sauce", "garlic", "ginger"], dietary: ["vegan", "gluten-free", "dairy-free"] },
    { name: "Buffalo Wings", ingredients: ["chicken wings", "hot sauce", "butter", "celery"], dietary: ["gluten-free"] },
    { name: "Banana Bread", ingredients: ["banana", "flour", "sugar", "egg", "butter"], dietary: ["vegetarian"] }
];